apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: rithvik2607/goserver:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "240m"
          limits:
            cpu: "2400m"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: goserver
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080